name: "Google Cloud SQL Proxy"
description: "Start Google CloudSQL Proxy"

branding:
  icon: "database"
  color: "red"

inputs:
  instance:
    description: "CloudSQL instance"
    required: true
  port:
    description: "Listen on port"
    required: false
    default: 5432

runs:
  using: "composite"
  steps:
    - name: Start Google Cloud SQL Proxy
      shell: bash
      run: |
        # Download Linux binary
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.15.1/cloud-sql-proxy.linux.amd64
        chmod +x cloud_sql_proxy

        # Start Cloud SQL Proxy
        ./cloud_sql_proxy --port ${{ inputs.port }} ${{ inputs.instance }}

        # wait until connections are accepted
        sleep 3
        isready=0
        for i in {1..10}; do
          echo "Wait for connections to be ready ... $i/10"
          (${{ github.action_path }}/wait-for-it.sh --quiet --timeout=3 --host=127.0.0.1 --port=${{ inputs.port }} || exit $?) && true # escape bash's pipefail
          isready=$?
          if [[ $isready -eq 0 ]]; then
            break
          fi
          sleep 2
        done

        # exit with error code if we couldn't connect
        if [[ $isready -ne 0 ]]; then
          exit $isready 
        fi
